#include "questions.hpp"

std::vector<Question> questions = {
    // Science Questions
    //----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    {"What is the basic unit of life?", {"Cell", "Tissue", "Organ", "Organism"}, 0},
    {"Which organelle is known as the powerhouse of the cell?", {"Nucleus", "Mitochondria", "Ribosome", "Chloroplast"}, 1},
    {"What pigment gives plants their green color?", {"Hemoglobin", "Melanin", "Chlorophyll", "Carotene"}, 2},
    {"Which process converts glucose into energy in cells?", {"Photosynthesis", "Respiration", "Fermentation", "Glycolysis"}, 1},
    {"What is the study of heredity called?", {"Ecology", "Genetics", "Botany", "Physiology"}, 1},
    {"What is the largest organ in the human body?", {"Liver", "Skin", "Heart", "Lungs"}, 1},
    {"Which macromolecule is primarily used for energy in living organisms?", {"Proteins", "Carbohydrates", "Lipids", "Nucleic acids"}, 1},
    {"What is the name of the process by which plants make their food?", {"Photosynthesis", "Respiration", "Digestion", "Fermentation"}, 0},
    {"Which part of the cell contains the genetic material?", {"Mitochondria", "Nucleus", "Ribosome", "Cytoplasm"}, 1},
    {"What is the chemical that carries genetic information?", {"RNA", "Protein", "DNA", "Lipids"}, 2},
    {"Which organ filters waste from the blood?", {"Liver", "Kidney", "Heart", "Lungs"}, 1},
    {"What are the building blocks of proteins?", {"Nucleotides", "Amino acids", "Fatty acids", "Monosaccharides"}, 1},
    {"What is the term for an organism that makes its own food?", {"Heterotroph", "Autotroph", "Decomposer", "Consumer"}, 1},
    {"What is the outermost layer of an animal cell?", {"Cell wall", "Plasma membrane", "Nucleus", "Cytoplasm"}, 1},
    {"Which system in the body is responsible for transporting nutrients and oxygen?", {"Digestive", "Respiratory", "Circulatory", "Nervous"}, 2},
    {"Which organ is part of the central nervous system?", {"Heart", "Brain", "Kidney", "Liver"}, 1},
    {"What type of blood vessels carry blood away from the heart?", {"Veins", "Arteries", "Capillaries", "Lymphatic vessels"}, 1},
    {"What is the term for the variety of all life forms on Earth?", {"Ecosystem", "Habitat", "Biodiversity", "Biome"}, 2},
    {"What is the structural and functional unit of the kidney?", {"Neuron", "Nephron", "Alveolus", "Capillary"}, 1},
    {"What type of reproduction involves only one parent?", {"Sexual reproduction", "Asexual reproduction", "Binary fission", "Fertilization"}, 1},
    {"What is the process by which cells divide to form two identical daughter cells?", {"Meiosis", "Mitosis", "Binary fission", "Replication"}, 1},
    {"Which organelle is responsible for photosynthesis?", {"Mitochondria", "Chloroplast", "Ribosome", "Nucleus"}, 1},
    {"What is the term for a change in an organism’s DNA?", {"Mutation", "Replication", "Transcription", "Translation"}, 0},
    {"What is the process by which water moves across a selectively permeable membrane?", {"Diffusion", "Osmosis", "Active transport", "Endocytosis"}, 1},
    {"What type of bond holds the two strands of DNA together?", {"Covalent bond", "Ionic bond", "Hydrogen bond", "Peptide bond"}, 2},
    {"What is the term for organisms that break down dead matter?", {"Producers", "Consumers", "Decomposers", "Autotrophs"}, 2},
    {"Which blood cells are involved in immune response?", {"Red blood cells", "White blood cells", "Platelets", "Plasma"}, 1},
    {"What type of biomolecule are enzymes?", {"Proteins", "Lipids", "Carbohydrates", "Nucleic acids"}, 0},
    {"What is the name of the process by which cells take in large molecules?", {"Exocytosis", "Endocytosis", "Osmosis", "Diffusion"}, 1},
    {"What is the primary function of the small intestine?", {"Absorb nutrients", "Filter toxins", "Store bile", "Break down proteins"}, 0},
    {"Which gas is released as a byproduct of photosynthesis?", {"Carbon dioxide", "Oxygen", "Nitrogen", "Methane"}, 1},
    {"Which system in the body controls hormones?", {"Nervous system", "Digestive system", "Endocrine system", "Respiratory system"}, 2},
    {"What is the main function of the liver?", {"Store oxygen", "Produce bile", "Regulate blood pressure", "Filter urine"}, 1},
    {"What are chromosomes made of?", {"RNA", "Lipids", "Proteins", "DNA"}, 3},
    {"Which organism is an example of a prokaryote?", {"Fungus", "Bacterium", "Plant", "Animal"}, 1},
    {"What is the term for a group of similar cells working together?", {"Tissue", "Organ", "Organ system", "Organism"}, 0},
    {"What is the name of the protein that carries oxygen in red blood cells?", {"Myoglobin", "Hemoglobin", "Fibrin", "Collagen"}, 1},
    {"What is the largest bone in the human body?", {"Femur", "Humerus", "Tibia", "Skull"}, 0},
    {"What is the name for the process of producing gametes?", {"Meiosis", "Mitosis", "Fertilization", "Oogenesis"}, 0},
    {"What is the basic structural unit of the nervous system?", {"Neuron", "Axon", "Dendrite", "Synapse"}, 0},
    {"What type of skeleton do humans have?", {"Exoskeleton", "Hydrostatic skeleton", "Endoskeleton", "Cartilaginous skeleton"}, 2},
    {"What is the term for the protective outer layer of a plant cell?", {"Cell membrane", "Cell wall", "Cytoplasm", "Chloroplast"}, 1},
    {"What is the function of ribosomes?", {"Store DNA", "Synthesize proteins", "Transport materials", "Generate energy"}, 1},
    {"Which hormone regulates blood sugar levels?", {"Insulin", "Adrenaline", "Thyroxine", "Glucagon"}, 0},
    {"What are the two types of nucleic acids?", {"RNA and DNA", "Proteins and RNA", "DNA and ATP", "Enzymes and DNA"}, 0},
    {"What is the term for the process of cell death?", {"Mitosis", "Meiosis", "Apoptosis", "Necrosis"}, 2},
    {"Which organ system is responsible for producing offspring?", {"Digestive system", "Respiratory system", "Reproductive system", "Nervous system"}, 2},
    {"What is the term for a group of ecosystems with similar climates?", {"Biome", "Population", "Community", "Biosphere"}, 0},
    {"What is the name of the protein that makes up hair and nails?", {"Keratin", "Collagen", "Elastin", "Fibrin"}, 0},
    {"What is the term for the symbiotic relationship where both organisms benefit?", {"Parasitism", "Mutualism", "Commensalism", "Competition"}, 1},
    {"What is the scientific study of animals called?", {"Botany", "Zoology", "Ecology", "Microbiology"}, 1},
    {"Which organ in the human body is primarily responsible for detoxification?", {"Kidney", "Liver", "Pancreas", "Spleen"}, 1},
    {"What is the primary photosynthetic pigment in plants?", {"Carotene", "Chlorophyll", "Xanthophyll", "Anthocyanin"}, 1},
    {"What is the term for the process by which plants lose water through their leaves?", {"Evaporation", "Transpiration", "Condensation", "Permeation"}, 1},
    {"Which organelle is responsible for protein synthesis?", {"Mitochondria", "Nucleus", "Endoplasmic reticulum", "Ribosome"}, 3},
    {"What is the main function of red blood cells?", {"Fight infections", "Carry oxygen", "Transport nutrients", "Control blood pressure"}, 1},
    {"Which part of the plant absorbs water and minerals from the soil?", {"Leaf", "Stem", "Root", "Flower"}, 2},
    {"Which process involves the movement of substances from an area of low concentration to an area of high concentration?", {"Diffusion", "Osmosis", "Active transport", "Facilitated diffusion"}, 2},
    {"Which part of the human body is responsible for pumping blood?", {"Brain", "Lungs", "Stomach", "Heart"}, 3},
    {"What is the term for an organism's ability to maintain stable internal conditions?", {"Metabolism", "Homeostasis", "Photosynthesis", "Respiration"}, 1},
    {"Which of these is not a part of the human respiratory system?", {"Lungs", "Trachea", "Esophagus", "Bronchi"}, 2},
    {"What is the main function of white blood cells?", {"Carry oxygen", "Clot blood", "Fight infections", "Transport nutrients"}, 2},
    {"What is the atomic number of Hydrogen?", {"1", "2", "3", "4"}, 0},
    {"Which element is represented by the symbol 'O'?", {"Ozone", "Osmium", "Oganesson", "Oxygen"}, 3},
    {"What is the most abundant element in Earth's crust?", {"Iron", "Silicon", "Aluminum", "Oxygen"}, 3},
    {"Which of the following is a noble gas?", {"Oxygen", "Nitrogen", "Argon", "Carbon"}, 2},
    {"What is the atomic number of Carbon?", {"4", "6", "8", "10"}, 1},
    {"Which element has the symbol 'Na'?", {"Sodium", "Neon", "Nitrogen", "Nickel"}, 0},
    {"What is the pH of pure water?", {"5", "6", "7", "8"}, 2},
    {"Which of the following is a halogen?", {"Oxygen", "Fluorine", "Carbon", "Nitrogen"}, 1},
    {"Which element is known for its role in the formation of acids?", {"Sulfur", "Hydrogen", "Nitrogen", "Chlorine"}, 1},
    {"What is the chemical symbol for Gold?", {"Au", "Ag", "Ga", "Ge"}, 0},
    {"Which of the following is a chemical property?", {"Density", "Boiling point", "Reactivity with acids", "Color"}, 2},
    {"What type of bond involves the sharing of electrons?", {"Ionic", "Covalent", "Metallic", "Hydrogen"}, 1},
    {"Which gas is most responsible for global warming?", {"Oxygen", "Carbon dioxide", "Nitrogen", "Methane"}, 1},
    {"Which metal is liquid at room temperature?", {"Mercury", "Aluminum", "Iron", "Lead"}, 0},
    {"Which of these compounds is a strong acid?", {"Acetic acid", "Citric acid", "Sulfuric acid", "Formic acid"}, 2},
    {"Which element is a non-metal and found in group 17?", {"Fluorine", "Neon", "Sodium", "Calcium"}, 0},
    {"What is the oxidation state of chlorine in NaCl?", {"-1", "0", "+1", "+2"}, 0},
    {"Which of the following is an example of a physical change?", {"Burning paper", "Dissolving salt in water", "Rusting of iron", "Rotting of food"}, 1},
    {"Which element is a part of all organic compounds?", {"Carbon", "Oxygen", "Hydrogen", "Nitrogen"}, 0},
    {"What is the name of the compound with the formula NaOH?", {"Sodium chloride", "Sodium hydroxide", "Sodium bicarbonate", "Sodium sulfate"}, 1},
    {"Which of the following elements is in the second period?", {"Lithium", "Boron", "Carbon", "Neon"}, 3},
    {"What is the process called when a liquid turns into a gas?", {"Condensation", "Evaporation", "Freezing", "Melting"}, 1},
    {"Which gas is produced when acids react with metals?", {"Hydrogen", "Oxygen", "Nitrogen", "Carbon dioxide"}, 0},
    {"What is the term for a solution that contains the maximum amount of solute?", {"Saturated", "Unsaturated", "Superheated", "Dilute"}, 0},
    {"Which of the following is an alkaline earth metal?", {"Sodium", "Calcium", "Magnesium", "Potassium"}, 1},
    {"What is the term for the number of protons in an atom?", {"Atomic number", "Mass number", "Electron number", "Isotope number"}, 0},
    {"Which molecule is responsible for the green color in plants?", {"Chlorophyll", "Carotene", "Anthocyanin", "Xanthophyll"}, 0},
    {"What is the chemical symbol for Lead?", {"Pb", "Li", "L", "Pd"}, 0},
    {"Which type of radiation has the highest energy?", {"Alpha", "Beta", "Gamma", "X-rays"}, 2},
    {"Which of the following is a characteristic of a base?", {"Sour taste", "Turns litmus paper red", "Slippery feel", "Releases H+ ions"}, 2},
    {"Which element is essential for the production of thyroid hormones?", {"Iodine", "Iron", "Magnesium", "Calcium"}, 0},
    {"What is the chemical symbol for the element with atomic number 8?", {"O", "N", "C", "F"}, 0},
    {"What is the process by which a solid turns directly into a gas?", {"Sublimation", "Melting", "Freezing", "Condensation"}, 0},
    {"Which of these elements is a noble gas?", {"Helium", "Hydrogen", "Nitrogen", "Oxygen"}, 0},
    {"Which of the following is a greenhouse gas?", {"Carbon dioxide", "Oxygen", "Hydrogen", "Neon"}, 0},
    {"Which element is commonly used in batteries?", {"Lithium", "Magnesium", "Iron", "Lead"}, 0},
    {"Which of these elements is in group 1 of the periodic table?", {"Sodium", "Boron", "Magnesium", "Calcium"}, 0},
    {"Which element is most commonly used in the semiconductor industry?", {"Silicon", "Germanium", "Gallium", "Carbon"}, 0},
    {"What type of chemical reaction involves the combination of two reactants to form a single product?", {"Decomposition", "Combination", "Single displacement", "Double displacement"}, 1},
    {"Which of the following is a property of metals?", {"Brittleness", "Non-conductive", "High melting point", "Non-shiny"}, 2},
    {"What is the term for the amount of space an object occupies?", {"Mass", "Volume", "Density", "Weight"}, 1},
    {"What is the chemical symbol for Potassium?", {"K", "P", "Pt", "Pa"}, 0},
    {"Which of these is an example of a chemical change?", {"Melting ice", "Boiling water", "Rusting iron", "Dissolving sugar in water"}, 2},
    {"Which of the following is a liquid at room temperature?", {"Oxygen", "Chlorine", "Mercury", "Hydrogen"}, 2},
    {"Which of the following is a product of photosynthesis?", {"Oxygen", "Carbon dioxide", "Nitrogen", "Water"}, 0},
    {"What is the atomic number of Nitrogen?", {"5", "7", "9", "11"}, 1},
    {"Which element has the symbol 'Fe'?", {"Iron", "Fluorine", "Francium", "Flerovium"}, 0},
    {"What is the chemical symbol for Silver?", {"Ag", "Si", "S", "Al"}, 0},
    {"What is the process of turning a gas into a liquid called?", {"Sublimation", "Condensation", "Evaporation", "Freezing"}, 1},
    {"What is the Earth's outermost layer?", {"Crust", "Mantle", "Core", "Lithosphere"}, 0},
    {"Which planet is known as the 'Red Planet'?", {"Mars", "Venus", "Earth", "Saturn"}, 0},
    {"What is the main component of Earth's atmosphere?", {"Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"}, 2},
    {"What type of rock forms from cooling and solidification of magma?", {"Sedimentary", "Igneous", "Metamorphic", "Limestone"}, 1},
    {"Which layer of the Earth is made of liquid iron and nickel?", {"Mantle", "Core", "Crust", "Outer Core"}, 3},
    {"Which gas contributes most to the greenhouse effect?", {"Methane", "Oxygen", "Carbon Dioxide", "Nitrogen"}, 2},
    {"What is the largest ocean on Earth?", {"Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"}, 3},
    {"What is the term for molten rock beneath the Earth’s surface?", {"Lava", "Magma", "Basalt", "Granite"}, 1},
    {"Which of the following is a non-renewable resource?", {"Wind", "Solar Energy", "Coal", "Geothermal Energy"}, 2},
    {"What is the process by which plants release water vapor into the atmosphere?", {"Transpiration", "Evaporation", "Precipitation", "Condensation"}, 0},
    {"Which type of plate boundary is characterized by plates moving away from each other?", {"Convergent", "Divergent", "Transform", "Subduction"}, 1},
    {"What is the deepest part of the world's oceans?", {"Mariana Trench", "Great Barrier Reef", "Puerto Rico Trench", "Mid-Atlantic Ridge"}, 0},
    {"What is the main cause of tides?", {"Wind", "Sun and Moon gravity", "Earth’s rotation", "Ocean currents"}, 1},
    {"Which is the hardest mineral on the Mohs scale?", {"Diamond", "Gold", "Emerald", "Quartz"}, 0},
    {"What is the term for the process of water turning into vapor?", {"Evaporation", "Precipitation", "Condensation", "Transpiration"}, 0},
    {"Which of the following is an example of a sedimentary rock?", {"Granite", "Basalt", "Sandstone", "Marble"}, 2},
    {"What is the Earth's primary source of energy?", {"Geothermal Energy", "Wind", "Solar Energy", "The Sun"}, 3},
    {"Which element is most abundant in the Earth’s crust?", {"Oxygen", "Silicon", "Iron", "Aluminum"}, 0},
    {"What phenomenon occurs when a tectonic plate moves beneath another?", {"Subduction", "Rifting", "Volcanic Activity", "Collision"}, 0},
    {"Which natural disaster is measured using the Richter scale?", {"Tsunami", "Earthquake", "Volcanic Eruption", "Flooding"}, 1},
    {"Which layer of the Earth's atmosphere contains the ozone layer?", {"Stratosphere", "Mesosphere", "Troposphere", "Exosphere"}, 0},
    {"What type of rock forms from the compression of sediment?", {"Sedimentary", "Igneous", "Metamorphic", "Basalt"}, 0},
    {"What does the term ‘fossil fuel’ refer to?", {"Coal, Oil, and Natural Gas", "Wood and Charcoal", "Nuclear Energy", "Geothermal Energy"}, 0},
    {"What is the process by which rocks break down into smaller pieces?", {"Erosion", "Weathering", "Sedimentation", "Metamorphism"}, 1},
    {"Which ocean is located to the west of the United States?", {"Atlantic Ocean", "Pacific Ocean", "Indian Ocean", "Arctic Ocean"}, 1},
    {"What does the term 'tectonic plates' refer to?", {"Crustal regions of Earth", "Continental landmasses", "Movable portions of Earth's lithosphere", "Underground water reserves"}, 2},
    {"What causes the Earth’s seasons?", {"Earth’s elliptical orbit", "Earth’s rotation", "Earth's tilt on its axis", "Sun's energy intensity"}, 2},
    {"What is the main gas emitted during volcanic eruptions?", {"Nitrogen", "Carbon Dioxide", "Oxygen", "Sulfur Dioxide"}, 1},
    {"What type of volcano is typically large and gently sloped?", {"Shield Volcano", "Cinder Cone", "Stratovolcano", "Fissure Volcano"}, 0},
    {"Which process causes the formation of clouds?", {"Condensation", "Evaporation", "Precipitation", "Transpiration"}, 0},
    {"Which of the following is a characteristic of metamorphic rocks?", {"They form from heat and pressure", "They form from cooling lava", "They are composed of minerals", "They are formed by biological processes"}, 0},
    {"What is the process by which rocks are heated, melted, and then cooled?", {"Metamorphism", "Sedimentation", "Crystallization", "Igneous Formation"}, 2},
    {"Which layer of the Earth is responsible for generating the planet's magnetic field?", {"Outer Core", "Inner Core", "Mantle", "Crust"}, 0},
    {"What is the most common type of cloud?", {"Cumulus", "Stratus", "Cirrus", "Nimbus"}, 0},
    {"What causes a lunar eclipse?", {"The Earth blocks the Sun’s light", "The Moon blocks the Sun’s light", "The Earth blocks the Moon’s light", "The Moon passes between the Earth and the Sun"}, 2},
    {"Which gas is primarily responsible for acid rain?", {"Oxygen", "Carbon Dioxide", "Sulfur Dioxide", "Methane"}, 2},
    {"Which of the following is a characteristic of the troposphere?", {"It contains the most weather events", "It is the outermost layer of the atmosphere", "It is made up of mostly nitrogen", "It contains the ozone layer"}, 0},
    {"What is the term for the moment when the Earth’s axis is tilted neither toward nor away from the Sun?", {"Equinox", "Solstice", "Aphelion", "Perihelion"}, 0},
    {"Which phenomenon occurs when cold air sinks and warms up?", {"Convection", "Advection", "Convergence", "Subsidence"}, 3},
    {"Which of the following is a renewable energy source?", {"Coal", "Natural Gas", "Solar Energy", "Nuclear Energy"}, 2},
    {"What is the term for a large, slow-moving river of ice?", {"Glacier", "Iceberg", "Tide", "Current"}, 0},
    {"What is the Earth's most abundant element?", {"Iron", "Oxygen", "Silicon", "Nitrogen"}, 1},
    {"What is the primary cause of earthquakes?", {"Plate movement", "Volcanic eruptions", "Meteorite impacts", "Tidal forces"}, 0},
    {"Which type of rock is formed from the cooling and solidification of magma?", {"Igneous", "Metamorphic", "Sedimentary", "Basaltic"}, 0},
    {"What does the term 'biosphere' refer to?", {"The zone where life exists", "The Earth's atmosphere", "The Earth's crust", "The Earth's oceans"}, 0},
    {"What is the Earth's atmosphere made of?", {"Nitrogen, Oxygen, and Other Gases", "Oxygen and Carbon Dioxide", "Water Vapor and Carbon Dioxide", "Oxygen and Nitrogen"}, 0},
    {"Which type of weather front causes thunderstorms?", {"Warm Front", "Cold Front", "Occluded Front", "Stationary Front"}, 1},
    {"Which element makes up most of the Earth’s core?", {"Nickel", "Oxygen", "Iron", "Silicon"}, 2},
    {"What is the process of the water cycle that involves water turning into clouds?", {"Evaporation", "Condensation", "Precipitation", "Transpiration"}, 1},
    {"What does the term ‘seismic waves’ refer to?", {"Waves generated by earthquakes", "Waves in the ocean", "Waves in the atmosphere", "Waves in the mantle"}, 0},
    {"What is the term for a sudden increase in volcanic activity?", {"Volcanic eruption", "Lava flow", "Seismic event", "Tectonic shift"}, 0},
    {"Which of the following is NOT a type of plate boundary?", {"Convergent", "Divergent", "Transform", "Circular"}, 3},
    {"What is the Earth’s largest continent?", {"Asia", "Africa", "North America", "South America"}, 0},
    {"What is the term for the rock layer above the mantle?", {"Lithosphere", "Crust", "Core", "Tectonic Plate"}, 1},
    {"Which layer of the Earth contains the most of the planet's mass?", {"Mantle", "Core", "Crust", "Lithosphere"}, 0},
    {"What is the term for the process by which mountains are formed?", {"Mountain building", "Subduction", "Erosion", "Sedimentation"}, 0},
    {"Which of the following is an example of a fossil fuel?", {"Coal", "Wind", "Solar Power", "Hydropower"}, 0},
    {"What is the term for the process of a liquid turning into a gas?", {"Condensation", "Evaporation", "Freezing", "Melting"}, 1},
    {"What is the term for a volcanic rock that cools quickly?", {"Obsidian", "Basalt", "Granite", "Limestone"}, 0},
    {"Which gas in the atmosphere helps shield the Earth from ultraviolet radiation?", {"Oxygen", "Carbon Dioxide", "Nitrogen", "Ozone"}, 3},
    {"Which of the following is a type of renewable resource?", {"Wind", "Coal", "Natural Gas", "Nuclear Power"}, 0},
    {"What type of volcano is known for its explosive eruptions?", {"Shield Volcano", "Cinder Cone", "Stratovolcano", "Fissure Volcano"}, 2},
    {"What is the main component of Earth's mantle?", {"Iron", "Oxygen", "Silicon", "Magnesium"}, 3},
    {"What type of rock forms when minerals crystallize from water?", {"Sedimentary", "Igneous", "Metamorphic", "Chemical Sedimentary"}, 3},
    {"Which of the following is the largest terrestrial biome?", {"Desert", "Tundra", "Tropical Rainforest", "Taiga"}, 2},
    {"What does the term 'hydrosphere' refer to?", {"Earth's oceans", "Earth's water", "Earth's atmosphere", "Earth's landmasses"}, 1},
    {"Which geological process leads to the formation of mountains?", {"Erosion", "Volcanic Activity", "Plate Tectonics", "Weathering"}, 2},
    {"Which layer of the Earth's atmosphere is closest to the surface?", {"Troposphere", "Stratosphere", "Mesosphere", "Exosphere"}, 0},
    {"What is the name of the effect that causes the deflection of winds and ocean currents due to Earth's rotation?", {"Coriolis Effect", "El Niño", "Jet Stream", "Solar Wind"}, 0},
    {"Which of the following is an example of an intrusive igneous rock?", {"Basalt", "Pumice", "Granite", "Obsidian"}, 2},
    {"What phenomenon is responsible for the Earth's magnetic field?", {"Convection in the mantle", "Movement of tectonic plates", "Convection in the outer core", "Gravitational pull of the moon"}, 2},
    {"What is the SI unit of force?", {"Joule", "Newton", "Pascal", "Watt"}, 1},
    {"Who is known as the father of modern physics?", {"Isaac Newton", "Albert Einstein", "Niels Bohr", "Galileo Galilei"}, 1},
    {"What is the charge of an electron?", {"+1", "-1", "0", "2"}, 1},
    {"What does the law of conservation of energy state?", {"Energy can be created", "Energy can be destroyed", "Energy can be transferred but not destroyed", "Energy is infinite"}, 2},
    {"Which of the following is a vector quantity?", {"Speed", "Distance", "Velocity", "Mass"}, 2},
    {"What is the boiling point of water in Celsius?", {"50°C", "75°C", "100°C", "150°C"}, 2},
    {"What does the symbol 'Δ' represent in physics?", {"Change", "Constant", "Sum", "Time"}, 0},
    {"What is the unit of electric current?", {"Ohm", "Ampere", "Volt", "Tesla"}, 1},
    {"Who discovered the electron?", {"Albert Einstein", "Isaac Newton", "J.J. Thomson", "Marie Curie"}, 2},
    {"What is the unit of frequency?", {"Hertz", "Newton", "Ampere", "Joule"}, 0},
    {"What is the energy stored in an object due to its position?", {"Kinetic Energy", "Gravitational Potential Energy", "Elastic Potential Energy", "Thermal Energy"}, 1},
    {"Which of these is a non-renewable energy source?", {"Solar", "Wind", "Natural Gas", "Hydroelectric"}, 2},
    {"What is the main component of the Sun?", {"Hydrogen", "Oxygen", "Carbon", "Nitrogen"}, 0},
    {"Who proposed the theory of relativity?", {"Isaac Newton", "Niels Bohr", "Albert Einstein", "Max Planck"}, 2},
    {"What is the SI unit of power?", {"Joule", "Newton", "Watt", "Volt"}, 2},
    {"What is the principle of superposition in waves?", {"Waves can never interact", "Waves add up to form a new wave", "Waves always cancel each other out", "Waves travel in straight lines"}, 1},
    {"What is the SI unit of energy?", {"Joule", "Newton", "Volt", "Watt"}, 0},
    {"What is the force of gravity between two objects proportional to?", {"Their masses", "The distance between them", "Their charge", "The amount of light they emit"}, 0},
    {"What does the term 'work' mean in physics?", {"Energy transfer by a force", "The same as power", "Energy stored in an object", "Force applied without movement"}, 0},
    {"What is the acceleration of an object in free fall?", {"10 m/s^2", "9.8 m/s^2", "9.0 m/s^2", "0 m/s^2"}, 1},
    {"What is the force that resists the motion of an object through a fluid?", {"Friction", "Air resistance", "Tension", "Gravitational force"}, 1},
    {"What is the unit of electric charge?", {"Volt", "Coulomb", "Ampere", "Joule"}, 1},
    {"Which of these is a fundamental force?", {"Electromagnetic force", "Centripetal force", "Frictional force", "Tension"}, 0},
    {"What is the law of inertia?", {"An object at rest will stay at rest", "An object in motion will stay in motion", "Both of the above", "Neither of the above"}, 2},
    {"What is the unit of pressure?", {"Newton", "Pascal", "Joule", "Watt"}, 1},
    {"What is the principle of conservation of momentum?", {"Momentum is always lost in a collision", "Momentum is always gained in a collision", "The total momentum of an isolated system remains constant", "Momentum can be created or destroyed"}, 2},
    {"Which particle is responsible for electromagnetic force?", {"Proton", "Neutron", "Electron", "Photon"}, 3},
    {"What is the maximum possible efficiency of an ideal machine?", {"100%", "90%", "50%", "25%"}, 0},
    {"Which type of wave requires a medium to travel?", {"Electromagnetic wave", "Sound wave", "Light wave", "Radio wave"}, 1},
    {"What is the unit of magnetic flux?", {"Tesla", "Weber", "Ampere", "Volt"}, 1},
    {"What type of energy is stored in a compressed spring?", {"Kinetic energy", "Gravitational potential energy", "Elastic potential energy", "Thermal energy"}, 2},
    {"What is the primary cause of the greenhouse effect?", {"Ozone depletion", "Carbon dioxide and methane", "Solar radiation", "Oxygen levels"}, 1},
    {"What is the unit of inductance?", {"Henry", "Tesla", "Ohm", "Farad"}, 0},
    {"What happens to the resistance of a conductor when temperature increases?", {"It decreases", "It stays the same", "It increases", "It fluctuates"}, 2},
    {"Which of these is a property of a black hole?", {"It emits light", "It has infinite density", "It absorbs all types of energy", "It is visible to the naked eye"}, 1},
    {"What is the relationship between wavelength and frequency?", {"Directly proportional", "Inversely proportional", "No relationship", "Proportional to the square of each other"}, 1},
    {"What is the effect of increasing temperature on the resistance of a semiconductor?", {"It increases", "It decreases", "It stays the same", "It fluctuates"}, 1},
    {"What is the force between two point charges proportional to?", {"The sum of their charges", "The square of the distance between them", "The product of their charges", "The square root of the distance"}, 2},
    {"Which of the following describes the phenomenon of refraction?", {"Light changes direction when passing through different mediums", "Light bends due to gravity", "Light bounces off a surface", "Light speeds up in denser media"}, 0},
    {"What is the speed of a wave proportional to?", {"Its wavelength", "Its frequency", "The product of its wavelength and frequency", "Its energy"}, 2},
    {"What does E = mc^2 represent?", {"Energy and mass are interchangeable", "Energy is equal to the mass of an object", "Mass is proportional to the speed of light", "Mass increases with speed"}, 0},
    {"Which of the following is an example of potential energy?", {"A moving car", "A stretched rubber band", "A rolling ball", "A vibrating string"}, 1},
    {"What is the SI unit of temperature?", {"Kelvin", "Celsius", "Fahrenheit", "Joule"}, 0},
    {"What does the Doppler effect describe?", {"The change in frequency due to the motion of the source or observer", "The bending of light in a medium", "The reflection of waves", "The interaction of waves in a medium"}, 0},
    {"What is the energy of a photon directly proportional to?", {"Its frequency", "Its wavelength", "Its speed", "Its charge"}, 0},
    {"What is the unit of magnetic field strength?", {"Tesla", "Ampere", "Volt", "Joule"}, 0},
    {"What is the most abundant element in the universe?", {"Hydrogen", "Oxygen", "Carbon", "Helium"}, 0},
    {"Which of these particles is most massive?", {"Electron", "Neutron", "Proton", "Photon"}, 1},
    {"What is the primary function of a transformer?", {"Increase voltage", "Decrease voltage", "Convert mechanical energy to electrical energy", "Store energy"}, 0},
    {"What is the principle behind a lever?", {"Mechanical advantage", "Electromagnetic induction", "Conservation of momentum", "Thermodynamic equilibrium"}, 0},
    {"Which period is known for the rise of dinosaurs?", {"Triassic", "Jurassic", "Cretaceous", "Permian"}, 1},
    {"What was the largest known land predator dinosaur?", {"Tyrannosaurus rex", "Spinosaurus", "Allosaurus", "Giganotosaurus"}, 1},
    {"What group of animals did dinosaurs evolve from?", {"Mammals", "Amphibians", "Reptiles", "Fish"}, 2},
    {"What was the primary cause of the mass extinction event that wiped out the dinosaurs?", {"Volcanic activity", "Meteor impact", "Climate change", "Disease"}, 1},
    {"Which period came immediately before the Jurassic period?", {"Triassic", "Cretaceous", "Permian", "Paleozoic"}, 0},
    {"What is the name of the fossilized tree resin that sometimes contains preserved dinosaur DNA?", {"Amber", "Jet", "Coal", "Slate"}, 0},
    {"What is the term for the process by which rocks are broken down by physical, chemical, or biological means?", {"Weathering", "Erosion", "Sedimentation", "Metamorphism"}, 0},
    {"Which of the following is an example of a renewable energy source?", {"Coal", "Natural Gas", "Solar Energy", "Nuclear Power"}, 2},
    {"What is the term for the boundary between two different air masses?", {"Front", "High pressure system", "Low pressure system", "Jet stream"}, 0},
    {"What is the most abundant gas in the Earth's atmosphere?", {"Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"}, 2},
    {"Which of the following types of volcanoes are the most explosive?", {"Cinder Cone", "Shield Volcano", "Stratovolcano", "Fissure Volcano"}, 2},
    {"What does the term 'hydrosphere' refer to?", {"The Earth's water", "The Earth's landmasses", "The Earth's atmosphere", "The Earth's magnetic field"}, 0},
    {"Which of the following is the largest type of mass wasting event?", {"Rockfall", "Mudslide", "Landslide", "Earthquake"}, 2},
    {"What is the term for the molten rock that erupts from a volcano?", {"Magma", "Lava", "Ash", "Gas"}, 1},
    {"What is the process by which water from the Earth's surface enters the atmosphere?", {"Condensation", "Evaporation", "Precipitation", "Transpiration"}, 1},
    {"What is the name of the supercontinent that existed around 200 million years ago?", {"Pangaea", "Rodinia", "Gondwana", "Laurasia"}, 0},
    {"What is the term for the measure of the amount of energy released during an earthquake?", {"Magnitude", "Intensity", "Frequency", "Amplitude"}, 0},
    {"What is the term for the increase in Earth's average temperature due to human activity?", {"Global warming", "Greenhouse effect", "Ozone depletion", "Acid rain"}, 0},
    //----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

    // IT Questions
    //----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    {"What does 'HTTP' stand for?", {"Hypertext Transfer Protocol", "Hypertext Transmission Protocol", "HyperTerminal Text Protocol", "Hyper Transfer Text Protocol"}, 0},
    {"Which of these is an example of an input device?", {"Monitor", "Printer", "Keyboard", "Speaker"}, 2},
    {"What is the main function of the CPU?", {"Store data", "Perform arithmetic operations", "Execute instructions", "Manage input devices"}, 2},
    {"Which of these is an operating system?", {"Microsoft Word", "Windows", "Google Chrome", "Microsoft Excel"}, 1},
    {"What does 'IP' stand for?", {"Internet Protocol", "Integrated Program", "Intelligent Processor", "Internal Process"}, 0},
    {"Which is a web browser?", {"Google Chrome", "Adobe Photoshop", "Microsoft Excel", "Visual Studio"}, 0},
    {"What does 'DNS' stand for?", {"Dynamic Network System", "Domain Name Service", "Direct Network Service", "Data Network System"}, 1},
    {"Which of these is a non-volatile memory?", {"RAM", "Cache", "SSD", "Registers"}, 2},
    {"What is the primary purpose of an operating system?", {"Run applications", "Provide security", "Manage hardware and software", "Store data"}, 2},
    {"What does 'BIOS' stand for?", {"Basic Integrated Operating System", "Binary Input Output System", "Basic Input Output System", "Basic Input Operating System"}, 2},
    {"Which of the following is NOT an example of cloud storage?", {"Google Drive", "Dropbox", "iCloud", "External Hard Drive"}, 3},
    {"Which device is used to connect multiple computers in a network?", {"Router", "Switch", "Printer", "Scanner"}, 1},
    {"Which of these is an object-oriented programming language?", {"C", "Java", "COBOL", "Fortran"}, 1},
    {"What does 'RAM' stand for?", {"Read Access Memory", "Random Access Memory", "Real Access Memory", "Rapid Access Memory"}, 1},
    {"What is the function of a firewall?", {"To protect a network from unauthorized access", "To store files", "To execute applications", "To increase network speed"}, 0},
    {"Which of these is an example of malware?", {"Virus", "Operating System", "Browser", "Spreadsheet"}, 0},
    {"What does 'URL' stand for?", {"Uniform Resource Locator", "Universal Resource Locator", "Uniform Resource List", "Universal Resource List"}, 0},
    {"Which programming language is widely used for web development?", {"C", "JavaScript", "Python", "Java"}, 1},
    {"What is the function of the ALU (Arithmetic Logic Unit)?", {"Manage memory", "Execute arithmetic and logical operations", "Store data", "Control input and output devices"}, 1},
    {"Which type of computer memory is used to store the BIOS?", {"ROM", "RAM", "Cache", "Hard Drive"}, 0},
    {"Which of the following is a type of database?", {"SQL", "HTML", "CSS", "JavaScript"}, 0},
    {"What does 'USB' stand for?", {"Universal Serial Bus", "Unified System Bus", "Universal System Board", "Universal Standard Bus"}, 0},
    {"Which of these is an example of a relational database?", {"Oracle", "MongoDB", "Redis", "Cassandra"}, 0},
    {"What does 'VPN' stand for?", {"Virtual Public Network", "Virtual Private Network", "Variable Private Network", "Virtual Program Network"}, 1},
    {"What does 'HTTP' use to transfer data over the web?", {"FTP", "SMTP", "TCP/IP", "UDP"}, 2},
    {"What is the primary function of an antivirus program?", {"To protect against malware", "To increase internet speed", "To store files", "To manage hardware resources"}, 0},
    {"Which of the following is a version control system?", {"Git", "MySQL", "Apache", "Microsoft Word"}, 0},
    {"Which of these is a popular operating system for mobile devices?", {"Linux", "Windows", "macOS", "Android"}, 3},
    {"What is the purpose of encryption?", {"To protect data from unauthorized access", "To improve network speed", "To backup data", "To store files securely"}, 0},
    {"Which of the following is an open-source software?", {"Windows", "macOS", "Linux", "iOS"}, 2},
    {"What is the function of an API?", {"To manage network traffic", "To allow different software to communicate", "To store data", "To protect against malware"}, 1},
    {"Which of these is a type of storage device?", {"RAM", "Hard Drive", "Cache", "Router"}, 1},
    {"What is the main function of the operating system kernel?", {"To provide a graphical user interface", "To manage hardware resources", "To run applications", "To increase processing speed"}, 1},
    {"Which of these is NOT a web server?", {"Apache", "nginx", "Tomcat", "WordPress"}, 3},
    {"Which is the function of a router in networking?", {"Store files", "Manage memory", "Direct traffic between networks", "Provide network security"}, 2},
    {"What does 'SSD' stand for?", {"Solid-State Drive", "Single Storage Disk", "Secure System Disk", "System Storage Drive"}, 0},
    {"What is the name of the software used for creating documents?", {"Microsoft Excel", "Microsoft Word", "Adobe Photoshop", "Google Chrome"}, 1},
    {"Which of the following is NOT a programming language?", {"Java", "C++", "Python", "Microsoft Office"}, 3},
    {"Which of the following is an example of an input device?", {"Monitor", "Keyboard", "Speaker", "Printer"}, 1},
    {"Which of these is a method of transferring files over the internet?", {"HTTP", "SMTP", "FTP", "DNS"}, 2},
    {"Which of the following is NOT a feature of an SSD?", {"Fast read/write speeds", "Low power consumption", "Higher cost", "Requires regular defragmentation"}, 3},
    {"Which of these is a popular cloud storage service?", {"Google Drive", "Photoshop", "Excel", "Notepad"}, 0},
    {"Which of the following is the correct extension for an image file?", {".txt", ".jpg", ".pdf", ".exe"}, 1},
    {"Which of the following is used to connect two computers directly?", {"Router", "Switch", "Hub", "Ethernet Cable"}, 3},
    {"What does 'RAM' stand for?", {"Read Access Memory", "Random Access Memory", "Rapid Access Memory", "Real-time Access Memory"}, 1},
    {"Which of the following is used to access the Internet?", {"Web Browser", "Operating System", "Word Processor", "File Explorer"}, 0},
    {"Which of these is a type of programming language?", {"HTML", "JavaScript", "MySQL", "Excel"}, 1},
    {"Which of these is the main function of an operating system?", {"Execute commands", "Manage hardware resources", "Store files", "Manage network traffic"}, 1},
    {"What does 'FTP' stand for?", {"File Transfer Protocol", "Fast Transfer Protocol", "File Transport Protocol", "Fast Traffic Protocol"}, 0},
    {"What is the purpose of a proxy server?", {"To manage file storage", "To increase processing speed", "To act as an intermediary between the client and server", "To protect against malware"}, 2},
    {"What does 'BIOS' do?", {"Control memory allocation", "Load the operating system", "Provide network security", "Store user data"}, 1},
    {"Which of these is an example of a relational database?", {"MongoDB", "Oracle", "Redis", "Cassandra"}, 1},
    {"Which of the following is NOT a function of an operating system?", {"Managing hardware resources", "Running applications", "Handling network requests", "Writing software code"}, 3},
    {"What is the name of the protocol used for email?", {"HTTP", "FTP", "IMAP", "SMTP"}, 3},
    {"What does 'SQL' stand for?", {"Structured Query Language", "Simple Query Language", "Standard Query Language", "Secure Query Language"}, 0},
    {"Which of these is a function of a database management system?", {"To create a network", "To store and organize data", "To manage user interfaces", "To run software applications"}, 1},
    {"Which of these is a type of cloud computing?", {"IaaS", "Windows", "Excel", "Google Chrome"}, 0},
    {"What is the main purpose of a hard drive?", {"To execute commands", "To store data permanently", "To manage hardware resources", "To display images"}, 1},
    {"What does 'URL' stand for?", {"Uniform Resource Locator", "Uniform Reference Locator", "Universal Resource Locator", "Universal Resource List"}, 0},
    {"Which of the following is NOT a type of computer memory?", {"RAM", "Cache", "SSD", "ROM"}, 2},
    {"Which of these is the best definition of cloud computing?", {"Computing done in physical data centers", "Using a remote server to store and manage data", "Using local servers to host applications", "Storing files on a computer's hard drive"}, 1},
    {"Which of these is a type of networking cable?", {"HDMI", "Ethernet", "USB", "VGA"}, 1},
    {"Which of these is an example of a database query language?", {"SQL", "Python", "Java", "HTML"}, 0},
    {"What is the main purpose of a router?", {"To execute software", "To store data", "To direct data traffic between devices on a network", "To display images"}, 2},
    {"Which of the following is an example of an input device?", {"Monitor", "Keyboard", "Speaker", "Printer"}, 1},
    {"What is the function of a compiler?", {"To manage hardware resources", "To translate source code into machine code", "To protect against viruses", "To store files"}, 1},
    {"Which of the following is a popular source control tool?", {"Apache", "Git", "SQL", "MySQL"}, 1},
    {"Which of these is a digital communication protocol?", {"FTP", "Ethernet", "USB", "SMTP"}, 3},
    {"What does 'IP address' stand for?", {"Internet Protocol address", "Internal Protocol address", "Internet Private address", "Internal Private address"}, 0},
    {"What does 'URL' stand for?", {"Uniform Resource Locator", "Universal Resource Locator", "United Resource Locator", "Universal Reference Locator"}, 0},
    {"What does 'Wi-Fi' stand for?", {"Wireless Fidelity", "Wireless Fast Internet", "Wireless Frequency", "Worldwide Internet Fidelity"}, 0},
    {"Which of these is NOT an operating system?", {"Windows", "MacOS", "Linux", "Microsoft Word"}, 3},
    {"Which of these is an example of system software?", {"Google Chrome", "Adobe Acrobat", "Windows", "Microsoft Word"}, 2},
    {"Which of these is an example of a programming language?", {"Python", "Excel", "Word", "PowerPoint"}, 0},
    {"What is the main role of the kernel in an operating system?", {"Manage user input", "Control hardware resources", "Execute applications", "Store files"}, 1},
    {"What is the purpose of an IP address?", {"Identify devices on a network", "Store files on a server", "Provide internet access", "Encrypt data on the network"}, 0},
    {"Which of these is NOT a web browser?", {"Google Chrome", "Mozilla Firefox", "Internet Explorer", "Microsoft Word"}, 3},
    {"What does 'GUI' stand for?", {"Graphical User Interface", "General User Interface", "Global User Interface", "Grid User Interface"}, 0},
    {"What is the function of a motherboard?", {"To execute programs", "To connect all hardware components", "To store data", "To provide network access"}, 1},
    {"What is an example of a virus in IT?", {"Worm", "Trojan", "Adware", "Spyware"}, 1},
    {"Which of these is an example of a non-volatile storage device?", {"RAM", "Cache", "Hard Drive", "Registers"}, 2},
    {"Which of these is the function of a file system?", {"To execute programs", "To manage files and directories", "To manage network connections", "To increase internet speed"}, 1},
    {"What does 'DNS' stand for?", {"Dynamic Network Service", "Domain Name System", "Data Network Service", "Digital Network System"}, 1},
    {"What does the term 'cloud computing' refer to?", {"Storing and managing data on remote servers", "Storing data on a local hard drive", "Accessing data from a server", "Sending emails through a server"}, 0},
    {"Which of these is a popular web development language?", {"Java", "HTML", "C++", "Python"}, 1},
    {"What is the function of a DNS server?", {"To store files", "To convert domain names into IP addresses", "To execute code", "To manage input devices"}, 1},
    {"Which of these is used for version control?", {"Git", "Linux", "Windows", "MySQL"}, 0},
    {"What is the purpose of encryption?", {"To protect data from unauthorized access", "To increase internet speed", "To store files securely", "To compress files"}, 0},
    {"Which of the following is an example of a type of software?", {"Java", "MySQL", "Photoshop", "All of the above"}, 3},
    {"Which of the following is an example of a cloud storage service?", {"Dropbox", "iCloud", "Google Drive", "All of the above"}, 3},
    {"What does 'SSH' stand for?", {"Secure Socket Host", "Secure Shell", "Shared Secure Host", "Secure Session Handler"}, 1},
    {"Which of these is NOT an example of an operating system?", {"Linux", "Windows", "macOS", "WordPress"}, 3},
    {"What is the main role of a server?", {"Store files", "Manage network traffic", "Host applications and data", "Provide user interfaces"}, 2},
    {"What does 'SQL' stand for?", {"Structured Query Language", "Simple Query Language", "Standard Query Language", "Sequential Query Language"}, 0},
    {"What does 'DNS' stand for?", {"Domain Name System", "Data Network Service", "Digital Name System", "Domain Network System"}, 0},
    {"Which of these is a cloud storage provider?", {"OneDrive", "Windows", "Android", "MacOS"}, 0},
    {"What does 'HTTP' stand for?", {"Hypertext Transfer Protocol", "Hyper Transfer Protocol", "Hyper Text Protocol", "Hyper Tool Protocol"}, 0},
    {"Which of these is a type of software?", {"Windows", "Google Chrome", "Facebook", "Microsoft Word"}, 1},
    {"What is the purpose of a router?", {"To store data", "To manage network traffic between devices", "To provide internet access", "To execute software programs"}, 1},
    {"What is the role of a compiler in programming?", {"To execute the program", "To convert source code into machine code", "To store data", "To manage memory usage"}, 1},
    {"Which of the following is an example of an input device?", {"Monitor", "Printer", "Keyboard", "Speaker"}, 2},
    {"What does 'URL' stand for?", {"Uniform Resource Locator", "Universal Resource Locator", "Uniform Realtime Locator", "Universal Reference Locator"}, 0},
    {"Which of these is a web development language?", {"HTML", "C++", "Python", "Java"}, 0},
    {"What is the function of an operating system?", {"Execute applications", "Manage hardware and software resources", "Store files", "Transmit data over the internet"}, 1},
    {"Which of the following is an example of a machine learning framework?", {"TensorFlow", "Windows", "MySQL", "C#"}, 0},
    {"What is the full form of 'Wi-Fi'?", {"Wireless Fidelity", "Worldwide Internet Frequency", "Wide Internet Format", "Wireless Frequency Indicator"}, 0},
    {"What does 'IDE' stand for in programming?", {"Integrated Development Environment", "Interface Development Environment", "Internal Development Engine", "Integrated Database Environment"}, 0},
    {"Which of the following is an example of a programming language?", {"Java", "Word", "Windows", "iOS"}, 0},
    {"What is the main purpose of an IP address?", {"To identify devices on a network", "To protect against malware", "To increase internet speed", "To store files securely"}, 0},
    {"Which of these is a type of cloud computing service?", {"IaaS", "SMTP", "HTML", "Google Drive"}, 0},
    {"What does 'SSH' stand for?", {"Secure Shell", "Secure System Hosting", "Simple Shell", "System Security Hub"}, 0},
    {"Which of these is used to connect a computer to a network?", {"Router", "Keyboard", "Monitor", "Hard Drive"}, 0},
    {"What is the function of the CPU?", {"Perform calculations and execute instructions", "Manage memory", "Store data", "Handle network traffic"}, 0},
    {"Which of these is an example of a digital communication protocol?", {"HTTP", "Java", "Python", "Excel"}, 0},
    {"What does 'API' stand for?", {"Application Programming Interface", "Advanced Program Integration", "Automated Programming Interface", "Application Program Interface"}, 0},
    {"What is the purpose of a firewall?", {"To protect against unauthorized access", "To manage internet speed", "To provide file storage", "To increase processing power"}, 0},
    {"Which of these is a version control system?", {"Git", "Python", "Java", "HTML"}, 0},
    {"Which of these is used for sending emails?", {"SMTP", "HTML", "FTP", "IP"}, 0},
    {"What is the function of a hard disk drive?", {"To store data permanently", "To process data", "To provide internet access", "To manage memory"}, 0},
    {"What does 'VPN' stand for?", {"Virtual Private Network", "Virtual Public Network", "Virtual Protected Network", "Vulnerable Private Network"}, 0},
    {"Which of these is a type of computer memory?", {"RAM", "CD-ROM", "Hard Disk", "CPU"}, 0},
    {"What is the purpose of encryption?", {"To secure data", "To speed up network traffic", "To store data", "To improve software performance"}, 0},
    {"What is the main function of an antivirus program?", {"To protect the computer from viruses and malware", "To manage network connections", "To store files", "To increase processing speed"}, 0},
    {"What is the purpose of a data backup?", {"To store a copy of important data", "To increase processing speed", "To provide network access", "To execute software programs"}, 0},
    {"Which of these is a type of software?", {"JavaScript", "Operating System", "Database", "All of the above"}, 3},
    {"What is 'Cloud Computing'?", {"Storing and accessing data via the internet", "Storing data on local computers", "Storing data in the RAM", "Storing files in USB drives"}, 0},
    {"Which of the following is a type of operating system?", {"Linux", "Java", "Excel", "Word"}, 0},
    {"What is the role of the motherboard?", {"To connect and manage all hardware components", "To store data", "To execute software", "To protect against malware"}, 0},
    {"Which of these is an example of a programming language?", {"C#", "Windows", "Excel", "Photoshop"}, 0},
    {"What is the primary function of a modem?", {"To convert digital signals to analog", "To manage network traffic", "To protect against malware", "To execute applications"}, 0},
    {"Which of these is an example of an open-source operating system?", {"Linux", "Windows", "macOS", "iOS"}, 0},
    {"Which of these is a popular web browser?", {"Google Chrome", "Microsoft Word", "Excel", "Photoshop"}, 0},
    {"What does 'ROM' stand for?", {"Read-Only Memory", "Random-Only Memory", "Real Online Memory", "Read-Oriented Memory"}, 0},
    {"What is the main role of a database?", {"Store and manage data", "Display images", "Control hardware", "Execute programs"}, 0},
    {"Which of these is a type of web server?", {"Apache", "PHP", "Java", "MySQL"}, 0},
    {"Which of the following is used for network communication?", {"TCP/IP", "C++", "MySQL", "WordPress"}, 0},
    {"Which programming language is used for developing Android apps?", {"Java", "Python", "C#", "HTML"}, 0},
    {"Which of these is used for version control in software development?", {"Git", "SQL", "HTML", "WordPress"}, 0},
    {"What does 'GUI' stand for?", {"Graphical User Interface", "Global User Interface", "General User Interface", "Graph User Interface"}, 0},
    {"Which of these is NOT an example of an input device?", {"Keyboard", "Mouse", "Monitor", "Scanner"}, 2},
    {"What is the function of a motherboard?", {"Connect and manage hardware components", "Store files", "Process data", "Execute commands"}, 0},
    {"What does 'URL' stand for?", {"Uniform Resource Locator", "Universal Resource Locator", "Uniform Realtime Locator", "Universal Resource Locator"}, 0},
    {"Which of these is used for programming a website?", {"HTML", "Python", "Java", "JavaScript"}, 0},
    {"What does 'USB' stand for?", {"Universal Serial Bus", "Uniform Serial Bus", "Universal System Bus", "Universal Service Bus"}, 0},
    {"Which of the following is NOT a part of the software development life cycle?", {"Analysis", "Design", "Debugging", "Testing"}, 2},
    {"What is a variable in programming?", {"A storage location in memory with a name", "A type of loop", "A function that stores values", "A type of algorithm"}, 0},
    {"Which of these is a programming language?", {"Python", "Photoshop", "Microsoft Word", "Excel"}, 0},
    {"What does 'int' represent in most programming languages?", {"Integer", "Interval", "Instruction", "Internet"}, 0},
    {"What is the purpose of a function in programming?", {"To group code that performs a specific task", "To store data", "To define a variable", "To handle input/output operations"}, 0},
    {"Which of these is a correct example of a variable declaration in Python?", {"x = 10", "int x = 10", "let x = 10", "var x = 10"}, 0},
    {"What does 'if' do in a program?", {"It executes a block of code based on a condition", "It defines a function", "It stores data", "It creates an object"}, 0},
    {"Which of these is a type of loop?", {"for loop", "variable loop", "math loop", "exit loop"}, 0},
    {"What is the purpose of a 'while' loop?", {"To repeat a block of code as long as a condition is true", "To store data", "To define a function", "To display a message"}, 0},
    {"What does 'array' mean in programming?", {"A collection of elements, typically of the same type", "A function to calculate values", "A type of variable", "A mathematical operation"}, 0},
    {"What is a 'string' in programming?", {"A sequence of characters", "A collection of numbers", "A variable type", "A type of loop"}, 0},
    {"What is the purpose of a 'break' statement in a loop?", {"To exit the loop", "To repeat the loop", "To define a condition", "To declare a variable"}, 0},
    {"Which of the following is NOT a valid data type?", {"boolean", "integer", "character", "loop"}, 3},
    {"What does the 'else' statement do?", {"It specifies a block of code to run when the 'if' condition is false", "It starts a loop", "It defines a variable", "It ends a function"}, 0},
    {"Which of these is used to comment a line of code in Python?", {"# Comment", "// Comment", "/* Comment */", "<!-- Comment -->"}, 0},
    {"What does 'return' do in a function?", {"It exits the function and sends a value back", "It starts a new loop", "It defines a new variable", "It handles user input"}, 0},
    {"Which of the following is a logical operator?", {"&&", "++", "==", "-="}, 0},
    {"What is an object in Object-Oriented Programming (OOP)?", {"An instance of a class", "A variable", "A function", "A data type"}, 0},
    {"What does 'class' mean in OOP?", {"A blueprint for creating objects", "A collection of variables", "A function", "A type of loop"}, 0},
    {"What is the result of the following code snippet: `print(2 + 3 * 4)` in Python?", {"14", "20", "8", "24"}, 0},
    {"What does 'def' do in Python?", {"Defines a function", "Declares a variable", "Starts a loop", "Checks a condition"}, 0},
    {"Which of these is a type of operator in programming?", {"Arithmetic", "Function", "Variable", "Loop"}, 0},
    {"What is the purpose of a 'for' loop?", {"To iterate over a sequence of elements", "To store data", "To define variables", "To exit a loop"}, 0},
    {"What does 'continue' do in a loop?", {"Skips the current iteration and moves to the next one", "Exits the loop", "Starts the loop over", "Executes the loop condition"}, 0},
    {"What is the syntax for a comment in C++?", {"// Comment", "# Comment", "/* Comment */", "<!-- Comment -->"}, 0},
    {"Which of the following is an example of a comparison operator?", {"==", "=", "+", "*"}, 0},
    {"What is recursion in programming?", {"A function calling itself", "A loop that repeats", "A data structure", "A variable assignment"}, 0},
    {"Which of these is used to store multiple values in a single variable in most languages?", {"Array", "Variable", "Function", "String"}, 0},
    {"What does 'elif' do in Python?", {"It is used to check another condition if the 'if' is false", "It is a function", "It ends a loop", "It defines a variable"}, 0},
    {"What is the purpose of the 'try' block?", {"To handle exceptions or errors", "To declare a variable", "To define a function", "To start a loop"}, 0},
    {"Which of these is an example of an immutable data type in Python?", {"String", "List", "Dictionary", "Set"}, 0},
    {"What is the correct way to create a function in JavaScript?", {"function myFunction() {}", "create myFunction() {}", "def myFunction() {}", "function: myFunction() {}"}, 0},
    {"What is the correct syntax for an 'if' statement in Python?", {"if condition:", "if (condition) {}", "if [condition]", "if condition then"}, 0},
    {"What is an algorithm?", {"A step-by-step procedure to solve a problem", "A type of loop", "A function that executes code", "A data structure"}, 0},
    {"What is the purpose of the 'else if' statement?", {"To check additional conditions if the initial 'if' condition is false", "To start a loop", "To define a new variable", "To exit a loop"}, 0},
    {"What does 'boolean' represent?", {"True or false values", "Whole numbers", "Floating point numbers", "Text data"}, 0},
    {"Which of the following is an example of a 'while' loop in Python?", {"while condition:", "for condition:", "do condition while:", "repeat condition until:"}, 0},
    {"What is a method in Object-Oriented Programming?", {"A function defined inside a class", "A type of loop", "A variable", "A class definition"}, 0},
    {"What does 'null' represent?", {"A variable with no value assigned", "A function", "A type of data", "An empty list"}, 0},
    {"Which of these is a valid Python list?", {"[1, 2, 3]", "{1, 2, 3}", "(1, 2, 3)", "[1; 2; 3]"}, 0},
    {"What is a constructor in Object-Oriented Programming?", {"A method used to initialize an object", "A function", "A loop", "A variable"}, 0},
    {"What does 'assert' do in Python?", {"Checks if a condition is true and raises an error if not", "Declares a variable", "Defines a function", "Starts a loop"}, 0},
    {"Which of these is a type of data structure?", {"Linked list", "Variable", "Function", "Operator"}, 0},
    {"What is the result of `5 // 2` in Python?", {"2", "2.5", "3", "5"}, 0},
    {"Which of these is an example of a 'for' loop in Python?", {"for i in range(10):", "for i = 0; i < 10; i++", "for (i = 0; i < 10; i++)", "for i: 1 to 10"}, 0},
    {"What is an exception in programming?", {"An error that occurs during program execution", "A type of loop", "A method", "A data structure"}, 0},
    {"What is a 'class' in Object-Oriented Programming?", {"A blueprint for creating objects", "A type of function", "A variable type", "A data structure"}, 0},
    {"What does 'break' do in a loop?", {"Exits the loop", "Repeats the loop", "Defines a new variable", "Starts a new loop iteration"}, 0},
    {"Which of the following is an example of a function?", {"def myFunction():", "int x = 10", "for i in range(10):", "print(x)"}, 0},
    {"What is the purpose of the 'return' keyword?", {"To send a value from a function back to the caller", "To exit a loop", "To define a variable", "To start a function"}, 0},
    {"Which of these is an example of a 'dictionary' in Python?", {"{'key': 'value'}", "[1, 2, 3]", "{1, 2, 3}", "(1, 2, 3)"}, 0},
    {"What is a loop in programming?", {"A control structure that repeats code until a condition is met", "A type of variable", "A method of input validation", "A data structure"}, 0},
    {"Which of the following is used to define a function in Python?", {"def", "function", "func", "create"}, 0},
    {"What does 'else' represent in an 'if' statement?", {"Code that executes when the 'if' condition is false", "Code that always executes", "A variable assignment", "A loop control statement"}, 0},
    {"Which of the following is an example of a 'for' loop in Python?", {"for i in range(5):", "for (i = 0; i < 5; i++)", "loop i = 0; i < 5;", "repeat i until 5"}, 0},
    {"Which data structure uses key-value pairs?", {"Dictionary", "List", "Array", "String"}, 0},
    {"What is the purpose of the 'continue' statement?", {"To skip the current iteration and continue with the next one", "To exit the loop", "To define a function", "To declare a variable"}, 0},
    {"What is an exception?", {"An error that occurs during program execution", "A loop that repeats indefinitely", "A function that takes input", "A type of variable"}, 0},
    {"What does '==' mean in most programming languages?", {"Equality comparison", "Assignment", "Addition", "Modulo"}, 0},
    {"Which of these is used to store a sequence of characters?", {"String", "List", "Set", "Array"}, 0},
    {"What is the term for when a function calls itself?", {"Recursion", "Iteration", "Abstraction", "Inheritance"}, 0},
    {"Which of these is an example of a 'while' loop?", {"while condition:", "for i in range(10):", "repeat until condition;", "loop condition until true;"}, 0},
    {"What is the purpose of a class in Object-Oriented Programming?", {"To define the blueprint for creating objects", "To store data", "To perform operations on data", "To iterate through data"}, 0},
    {"What does the 'break' statement do in a loop?", {"Exits the loop immediately", "Skips the current iteration", "Defines a new function", "Declares a variable"}, 0},
    {"What is the difference between '==' and '===' in programming?", {"'==' compares values, '===' compares both values and types", "'==' compares types, '===' compares values", "'==' is used for functions, '===' for loops", "'==' is an assignment operator, '===' is a comparison"}, 0},
    {"What is an array?", {"A collection of elements of the same type", "A function that performs an operation", "A variable that stores data", "A conditional statement"}, 0},
    {"Which of these is an example of a 'for' loop in C++?", {"for(int i = 0; i < 10; i++)", "for i = 0 to 10", "repeat 10 times", "for i in range(10):"}, 0},
    {"What is a boolean data type?", {"A data type that can be either True or False", "A data type that stores text", "A data type used for floating-point numbers", "A data type used to store integers"}, 0},
    {"Which of these is a valid Python dictionary?", {"{'key': 'value'}", "[key: value]", "<key, value>", "(key = value)"}, 0},
    {"What does the 'input' function do in Python?", {"Accepts user input from the console", "Outputs data to the console", "Stores data in a variable", "Executes a function"}, 0},
    {"What is an identifier in programming?", {"A name given to variables, functions, or other elements", "A keyword in programming", "A special type of operator", "A kind of data structure"}, 0},
    {"Which of these is used for looping in Python?", {"for", "loop", "while", "both A and C"}, 3},
    {"What is an operator in programming?", {"A symbol that performs an operation on variables or values", "A variable in a program", "A function that performs a task", "A type of data structure"}, 0},
    {"What is the term for a function that returns another function?", {"Higher-order function", "Recursive function", "Anonymous function", "Nested function"}, 0},
    {"What is the purpose of the 'return' statement?", {"To send a result back from a function", "To exit a loop", "To define a variable", "To perform a calculation"}, 0},
    {"Which of these is an example of an immutable data type?", {"String", "List", "Dictionary", "Set"}, 0},
    {"What is the difference between '&&' and 'and' in programming?", {"'&&' is used in some languages (like C++), while 'and' is used in Python", "'&&' is for logical negation, 'and' for comparison", "'&&' and 'and' are the same", "'&&' is used for strings, 'and' for numbers"}, 0},
    {"Which of the following is a programming language?", {"JavaScript", "Java", "Ruby", "All of the above"}, 3},
    {"What does 'elif' stand for in Python?", {"Else if", "Else loop", "Else inline", "Else conditional"}, 0},
    {"Which of the following is an example of a conditional statement?", {"if", "for", "while", "def"}, 0},
    {"What is the purpose of the 'else' clause?", {"It defines code to execute if the condition is false", "It defines code to execute if the condition is true", "It breaks a loop", "It returns a result from a function"}, 0},
    {"Which of the following is a type of error in programming?", {"Syntax error", "Runtime error", "Logic error", "All of the above"}, 3},
    {"What is a method in Object-Oriented Programming?", {"A function that is associated with an object", "A type of variable", "A loop that repeats actions", "A conditional statement"}, 0},
    {"What does 'continue' do in a loop?", {"It skips the current iteration and continues with the next one", "It exits the loop", "It starts a new loop", "It defines a condition for the loop"}, 0},
    {"What is the purpose of the 'pass' statement in Python?", {"To do nothing, used as a placeholder", "To return a value", "To exit a loop", "To define a class"}, 0},
    {"Which of these is an example of a 'while' loop?", {"while i < 10:", "for i in range(10):", "repeat i until 10", "for i = 0; i < 10; i++"}, 0},
    {"Which of these is an example of a function in JavaScript?", {"function myFunction() {}", "myFunction function {}", "func myFunction() {}", "function: myFunction() {}"}, 0},
    {"What is the purpose of the 'break' statement in Python?", {"It exits the current loop", "It defines a function", "It starts a new iteration", "It skips the loop's current iteration"}, 0},
    {"Which of the following is an example of a logical operator?", {"and", "or", "not", "All of the above"}, 3},
    {"What is a nested loop?", {"A loop inside another loop", "A loop with multiple conditions", "A loop that calls a function", "A loop that iterates over multiple variables"}, 0},
    {"Which of the following is used to define a function in Java?", {"public static void myFunction()", "def myFunction()", "function myFunction()", "func myFunction()"}, 0},
    {"What does the 'input()' function do in Python?", {"It reads a line of text from the user", "It displays text to the user", "It stores user input in a variable", "It executes a function"}, 0},
    {"What is the default value of an uninitialized variable in JavaScript?", {"undefined", "null", "0", "NaN"}, 0},
    {"Which of these is used to loop through a range of numbers in Python?", {"range()", "loop()", "iterate()", "repeat()"}, 0},
    {"What is the purpose of the 'global' keyword in Python?", {"To declare a global variable inside a function", "To define a global function", "To iterate through global variables", "To access local variables globally"}, 0},
    {"What is the result of the following expression: `5 % 2`?", {"1", "2", "5", "0"}, 0},
    {"Which of the following is NOT a valid variable name in Python?", {"2ndVariable", "_variable", "variable2", "variable_name"}, 0},
    {"What does 'else if' represent in most programming languages?", {"A conditional statement that checks another condition", "A loop", "A method", "A data structure"}, 0},
    {"What is the use of the 'try' block?", {"To handle exceptions in a program", "To define a function", "To declare variables", "To start a loop"}, 0},
    {"What does the term 'iteration' refer to in programming?", {"Repeating a block of code multiple times", "Defining a function", "Declaring a variable", "Handling errors"}, 0}
    //----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

};

std::vector<Question> GetQuestionsVector() {
    return questions;
}
