#include "questions.hpp"

std::vector<Question> questions = {
    // IT Questions
    //----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    {"What does 'HTTP' stand for?", {"Hypertext Transfer Protocol", "Hypertext Transmission Protocol", "HyperTerminal Text Protocol", "Hyper Transfer Text Protocol"}, 0},
    {"Which of these is an example of an input device?", {"Monitor", "Printer", "Keyboard", "Speaker"}, 2},
    {"What is the main function of the CPU?", {"Store data", "Perform arithmetic operations", "Execute instructions", "Manage input devices"}, 2},
    {"Which of these is an operating system?", {"Microsoft Word", "Windows", "Google Chrome", "Microsoft Excel"}, 1},
    {"What does 'IP' stand for?", {"Internet Protocol", "Integrated Program", "Intelligent Processor", "Internal Process"}, 0},
    {"Which is a web browser?", {"Google Chrome", "Adobe Photoshop", "Microsoft Excel", "Visual Studio"}, 0},
    {"What does 'DNS' stand for?", {"Dynamic Network System", "Domain Name Service", "Direct Network Service", "Data Network System"}, 1},
    {"Which of these is a non-volatile memory?", {"RAM", "Cache", "SSD", "Registers"}, 2},
    {"What is the primary purpose of an operating system?", {"Run applications", "Provide security", "Manage hardware and software", "Store data"}, 2},
    {"What does 'BIOS' stand for?", {"Basic Integrated Operating System", "Binary Input Output System", "Basic Input Output System", "Basic Input Operating System"}, 2},
    {"Which of the following is NOT an example of cloud storage?", {"Google Drive", "Dropbox", "iCloud", "External Hard Drive"}, 3},
    {"Which device is used to connect multiple computers in a network?", {"Router", "Switch", "Printer", "Scanner"}, 1},
    {"Which of these is an object-oriented programming language?", {"C", "Java", "COBOL", "Fortran"}, 1},
    {"What does 'RAM' stand for?", {"Read Access Memory", "Random Access Memory", "Real Access Memory", "Rapid Access Memory"}, 1},
    {"What is the function of a firewall?", {"To protect a network from unauthorized access", "To store files", "To execute applications", "To increase network speed"}, 0},
    {"Which of these is an example of malware?", {"Virus", "Operating System", "Browser", "Spreadsheet"}, 0},
    {"What does 'URL' stand for?", {"Uniform Resource Locator", "Universal Resource Locator", "Uniform Resource List", "Universal Resource List"}, 0},
    {"Which programming language is widely used for web development?", {"C", "JavaScript", "Python", "Java"}, 1},
    {"What is the function of the ALU (Arithmetic Logic Unit)?", {"Manage memory", "Execute arithmetic and logical operations", "Store data", "Control input and output devices"}, 1},
    {"Which type of computer memory is used to store the BIOS?", {"ROM", "RAM", "Cache", "Hard Drive"}, 0},
    {"Which of the following is a type of database?", {"SQL", "HTML", "CSS", "JavaScript"}, 0},
    {"What does 'USB' stand for?", {"Universal Serial Bus", "Unified System Bus", "Universal System Board", "Universal Standard Bus"}, 0},
    {"Which of these is an example of a relational database?", {"Oracle", "MongoDB", "Redis", "Cassandra"}, 0},
    {"What does 'VPN' stand for?", {"Virtual Public Network", "Virtual Private Network", "Variable Private Network", "Virtual Program Network"}, 1},
    {"What does 'HTTP' use to transfer data over the web?", {"FTP", "SMTP", "TCP/IP", "UDP"}, 2},
    {"What is the primary function of an antivirus program?", {"To protect against malware", "To increase internet speed", "To store files", "To manage hardware resources"}, 0},
    {"Which of the following is a version control system?", {"Git", "MySQL", "Apache", "Microsoft Word"}, 0},
    {"Which of these is a popular operating system for mobile devices?", {"Linux", "Windows", "macOS", "Android"}, 3},
    {"What is the purpose of encryption?", {"To protect data from unauthorized access", "To improve network speed", "To backup data", "To store files securely"}, 0},
    {"Which of the following is an open-source software?", {"Windows", "macOS", "Linux", "iOS"}, 2},
    {"What is the function of an API?", {"To manage network traffic", "To allow different software to communicate", "To store data", "To protect against malware"}, 1},
    {"Which of these is a type of storage device?", {"RAM", "Hard Drive", "Cache", "Router"}, 1},
    {"What is the main function of the operating system kernel?", {"To provide a graphical user interface", "To manage hardware resources", "To run applications", "To increase processing speed"}, 1},
    {"Which of these is NOT a web server?", {"Apache", "nginx", "Tomcat", "WordPress"}, 3},
    {"Which is the function of a router in networking?", {"Store files", "Manage memory", "Direct traffic between networks", "Provide network security"}, 2},
    {"What does 'SSD' stand for?", {"Solid-State Drive", "Single Storage Disk", "Secure System Disk", "System Storage Drive"}, 0},
    {"What is the name of the software used for creating documents?", {"Microsoft Excel", "Microsoft Word", "Adobe Photoshop", "Google Chrome"}, 1},
    {"Which of the following is NOT a programming language?", {"Java", "C++", "Python", "Microsoft Office"}, 3},
    {"Which of the following is an example of an input device?", {"Monitor", "Keyboard", "Speaker", "Printer"}, 1},
    {"Which of these is a method of transferring files over the internet?", {"HTTP", "SMTP", "FTP", "DNS"}, 2},
    {"Which of the following is NOT a feature of an SSD?", {"Fast read/write speeds", "Low power consumption", "Higher cost", "Requires regular defragmentation"}, 3},
    {"Which of these is a popular cloud storage service?", {"Google Drive", "Photoshop", "Excel", "Notepad"}, 0},
    {"Which of the following is the correct extension for an image file?", {".txt", ".jpg", ".pdf", ".exe"}, 1},
    {"Which of the following is used to connect two computers directly?", {"Router", "Switch", "Hub", "Ethernet Cable"}, 3},
    {"What does 'RAM' stand for?", {"Read Access Memory", "Random Access Memory", "Rapid Access Memory", "Real-time Access Memory"}, 1},
    {"Which of the following is used to access the Internet?", {"Web Browser", "Operating System", "Word Processor", "File Explorer"}, 0},
    {"Which of these is a type of programming language?", {"HTML", "JavaScript", "MySQL", "Excel"}, 1},
    {"Which of these is the main function of an operating system?", {"Execute commands", "Manage hardware resources", "Store files", "Manage network traffic"}, 1},
    {"What does 'FTP' stand for?", {"File Transfer Protocol", "Fast Transfer Protocol", "File Transport Protocol", "Fast Traffic Protocol"}, 0},
    {"What is the purpose of a proxy server?", {"To manage file storage", "To increase processing speed", "To act as an intermediary between the client and server", "To protect against malware"}, 2},
    {"What does 'BIOS' do?", {"Control memory allocation", "Load the operating system", "Provide network security", "Store user data"}, 1},
    {"Which of these is an example of a relational database?", {"MongoDB", "Oracle", "Redis", "Cassandra"}, 1},
    {"Which of the following is NOT a function of an operating system?", {"Managing hardware resources", "Running applications", "Handling network requests", "Writing software code"}, 3},
    {"What is the name of the protocol used for email?", {"HTTP", "FTP", "IMAP", "SMTP"}, 3},
    {"What does 'SQL' stand for?", {"Structured Query Language", "Simple Query Language", "Standard Query Language", "Secure Query Language"}, 0},
    {"Which of these is a function of a database management system?", {"To create a network", "To store and organize data", "To manage user interfaces", "To run software applications"}, 1},
    {"Which of these is a type of cloud computing?", {"IaaS", "Windows", "Excel", "Google Chrome"}, 0},
    {"What is the main purpose of a hard drive?", {"To execute commands", "To store data permanently", "To manage hardware resources", "To display images"}, 1},
    {"What does 'URL' stand for?", {"Uniform Resource Locator", "Uniform Reference Locator", "Universal Resource Locator", "Universal Resource List"}, 0},
    {"Which of the following is NOT a type of computer memory?", {"RAM", "Cache", "SSD", "ROM"}, 2},
    {"Which of these is the best definition of cloud computing?", {"Computing done in physical data centers", "Using a remote server to store and manage data", "Using local servers to host applications", "Storing files on a computer's hard drive"}, 1},
    {"Which of these is a type of networking cable?", {"HDMI", "Ethernet", "USB", "VGA"}, 1},
    {"Which of these is an example of a database query language?", {"SQL", "Python", "Java", "HTML"}, 0},
    {"What is the main purpose of a router?", {"To execute software", "To store data", "To direct data traffic between devices on a network", "To display images"}, 2},
    {"Which of the following is an example of an input device?", {"Monitor", "Keyboard", "Speaker", "Printer"}, 1},
    {"What is the function of a compiler?", {"To manage hardware resources", "To translate source code into machine code", "To protect against viruses", "To store files"}, 1},
    {"Which of the following is a popular source control tool?", {"Apache", "Git", "SQL", "MySQL"}, 1},
    {"Which of these is a digital communication protocol?", {"FTP", "Ethernet", "USB", "SMTP"}, 3},
    {"What does 'IP address' stand for?", {"Internet Protocol address", "Internal Protocol address", "Internet Private address", "Internal Private address"}, 0},
    {"What does 'URL' stand for?", {"Uniform Resource Locator", "Universal Resource Locator", "United Resource Locator", "Universal Reference Locator"}, 0},
    {"What does 'Wi-Fi' stand for?", {"Wireless Fidelity", "Wireless Fast Internet", "Wireless Frequency", "Worldwide Internet Fidelity"}, 0},
    {"Which of these is NOT an operating system?", {"Windows", "MacOS", "Linux", "Microsoft Word"}, 3},
    {"Which of these is an example of system software?", {"Google Chrome", "Adobe Acrobat", "Windows", "Microsoft Word"}, 2},
    {"Which of these is an example of a programming language?", {"Python", "Excel", "Word", "PowerPoint"}, 0},
    {"What is the main role of the kernel in an operating system?", {"Manage user input", "Control hardware resources", "Execute applications", "Store files"}, 1},
    {"What is the purpose of an IP address?", {"Identify devices on a network", "Store files on a server", "Provide internet access", "Encrypt data on the network"}, 0},
    {"Which of these is NOT a web browser?", {"Google Chrome", "Mozilla Firefox", "Internet Explorer", "Microsoft Word"}, 3},
    {"What does 'GUI' stand for?", {"Graphical User Interface", "General User Interface", "Global User Interface", "Grid User Interface"}, 0},
    {"What is the function of a motherboard?", {"To execute programs", "To connect all hardware components", "To store data", "To provide network access"}, 1},
    {"What is an example of a virus in IT?", {"Worm", "Trojan", "Adware", "Spyware"}, 1},
    {"Which of these is an example of a non-volatile storage device?", {"RAM", "Cache", "Hard Drive", "Registers"}, 2},
    {"Which of these is the function of a file system?", {"To execute programs", "To manage files and directories", "To manage network connections", "To increase internet speed"}, 1},
    {"What does 'DNS' stand for?", {"Dynamic Network Service", "Domain Name System", "Data Network Service", "Digital Network System"}, 1},
    {"What does the term 'cloud computing' refer to?", {"Storing and managing data on remote servers", "Storing data on a local hard drive", "Accessing data from a server", "Sending emails through a server"}, 0},
    {"Which of these is a popular web development language?", {"Java", "HTML", "C++", "Python"}, 1},
    {"What is the function of a DNS server?", {"To store files", "To convert domain names into IP addresses", "To execute code", "To manage input devices"}, 1},
    {"Which of these is used for version control?", {"Git", "Linux", "Windows", "MySQL"}, 0},
    {"What is the purpose of encryption?", {"To protect data from unauthorized access", "To increase internet speed", "To store files securely", "To compress files"}, 0},
    {"Which of the following is an example of a type of software?", {"Java", "MySQL", "Photoshop", "All of the above"}, 3},
    {"Which of the following is an example of a cloud storage service?", {"Dropbox", "iCloud", "Google Drive", "All of the above"}, 3},
    {"What does 'SSH' stand for?", {"Secure Socket Host", "Secure Shell", "Shared Secure Host", "Secure Session Handler"}, 1},
    {"Which of these is NOT an example of an operating system?", {"Linux", "Windows", "macOS", "WordPress"}, 3},
    {"What is the main role of a server?", {"Store files", "Manage network traffic", "Host applications and data", "Provide user interfaces"}, 2},
    {"What does 'SQL' stand for?", {"Structured Query Language", "Simple Query Language", "Standard Query Language", "Sequential Query Language"}, 0},
    {"What does 'DNS' stand for?", {"Domain Name System", "Data Network Service", "Digital Name System", "Domain Network System"}, 0},
    {"Which of these is a cloud storage provider?", {"OneDrive", "Windows", "Android", "MacOS"}, 0},
    {"What does 'HTTP' stand for?", {"Hypertext Transfer Protocol", "Hyper Transfer Protocol", "Hyper Text Protocol", "Hyper Tool Protocol"}, 0},
    {"Which of these is a type of software?", {"Windows", "Google Chrome", "Facebook", "Microsoft Word"}, 1},
    {"What is the purpose of a router?", {"To store data", "To manage network traffic between devices", "To provide internet access", "To execute software programs"}, 1},
    {"What is the role of a compiler in programming?", {"To execute the program", "To convert source code into machine code", "To store data", "To manage memory usage"}, 1},
    {"Which of the following is an example of an input device?", {"Monitor", "Printer", "Keyboard", "Speaker"}, 2},
    {"What does 'URL' stand for?", {"Uniform Resource Locator", "Universal Resource Locator", "Uniform Realtime Locator", "Universal Reference Locator"}, 0},
    {"Which of these is a web development language?", {"HTML", "C++", "Python", "Java"}, 0},
    {"What is the function of an operating system?", {"Execute applications", "Manage hardware and software resources", "Store files", "Transmit data over the internet"}, 1},
    {"Which of the following is an example of a machine learning framework?", {"TensorFlow", "Windows", "MySQL", "C#"}, 0},
    {"What is the full form of 'Wi-Fi'?", {"Wireless Fidelity", "Worldwide Internet Frequency", "Wide Internet Format", "Wireless Frequency Indicator"}, 0},
    {"What does 'IDE' stand for in programming?", {"Integrated Development Environment", "Interface Development Environment", "Internal Development Engine", "Integrated Database Environment"}, 0},
    {"Which of the following is an example of a programming language?", {"Java", "Word", "Windows", "iOS"}, 0},
    {"What is the main purpose of an IP address?", {"To identify devices on a network", "To protect against malware", "To increase internet speed", "To store files securely"}, 0},
    {"Which of these is a type of cloud computing service?", {"IaaS", "SMTP", "HTML", "Google Drive"}, 0},
    {"What does 'SSH' stand for?", {"Secure Shell", "Secure System Hosting", "Simple Shell", "System Security Hub"}, 0},
    {"Which of these is used to connect a computer to a network?", {"Router", "Keyboard", "Monitor", "Hard Drive"}, 0},
    {"What is the function of the CPU?", {"Perform calculations and execute instructions", "Manage memory", "Store data", "Handle network traffic"}, 0},
    {"Which of these is an example of a digital communication protocol?", {"HTTP", "Java", "Python", "Excel"}, 0},
    {"What does 'API' stand for?", {"Application Programming Interface", "Advanced Program Integration", "Automated Programming Interface", "Application Program Interface"}, 0},
    {"What is the purpose of a firewall?", {"To protect against unauthorized access", "To manage internet speed", "To provide file storage", "To increase processing power"}, 0},
    {"Which of these is a version control system?", {"Git", "Python", "Java", "HTML"}, 0},
    {"Which of these is used for sending emails?", {"SMTP", "HTML", "FTP", "IP"}, 0},
    {"What is the function of a hard disk drive?", {"To store data permanently", "To process data", "To provide internet access", "To manage memory"}, 0},
    {"What does 'VPN' stand for?", {"Virtual Private Network", "Virtual Public Network", "Virtual Protected Network", "Vulnerable Private Network"}, 0},
    {"Which of these is a type of computer memory?", {"RAM", "CD-ROM", "Hard Disk", "CPU"}, 0},
    {"What is the purpose of encryption?", {"To secure data", "To speed up network traffic", "To store data", "To improve software performance"}, 0},
    {"What is the main function of an antivirus program?", {"To protect the computer from viruses and malware", "To manage network connections", "To store files", "To increase processing speed"}, 0},
    {"What is the purpose of a data backup?", {"To store a copy of important data", "To increase processing speed", "To provide network access", "To execute software programs"}, 0},
    {"Which of these is a type of software?", {"JavaScript", "Operating System", "Database", "All of the above"}, 3},
    {"What is 'Cloud Computing'?", {"Storing and accessing data via the internet", "Storing data on local computers", "Storing data in the RAM", "Storing files in USB drives"}, 0},
    {"Which of the following is a type of operating system?", {"Linux", "Java", "Excel", "Word"}, 0},
    {"What is the role of the motherboard?", {"To connect and manage all hardware components", "To store data", "To execute software", "To protect against malware"}, 0},
    {"Which of these is an example of a programming language?", {"C#", "Windows", "Excel", "Photoshop"}, 0},
    {"What is the primary function of a modem?", {"To convert digital signals to analog", "To manage network traffic", "To protect against malware", "To execute applications"}, 0},
    {"Which of these is an example of an open-source operating system?", {"Linux", "Windows", "macOS", "iOS"}, 0},
    {"Which of these is a popular web browser?", {"Google Chrome", "Microsoft Word", "Excel", "Photoshop"}, 0},
    {"What does 'ROM' stand for?", {"Read-Only Memory", "Random-Only Memory", "Real Online Memory", "Read-Oriented Memory"}, 0},
    {"What is the main role of a database?", {"Store and manage data", "Display images", "Control hardware", "Execute programs"}, 0},
    {"Which of these is a type of web server?", {"Apache", "PHP", "Java", "MySQL"}, 0},
    {"Which of the following is used for network communication?", {"TCP/IP", "C++", "MySQL", "WordPress"}, 0},
    {"Which programming language is used for developing Android apps?", {"Java", "Python", "C#", "HTML"}, 0},
    {"Which of these is used for version control in software development?", {"Git", "SQL", "HTML", "WordPress"}, 0},
    {"What does 'GUI' stand for?", {"Graphical User Interface", "Global User Interface", "General User Interface", "Graph User Interface"}, 0},
    {"Which of these is NOT an example of an input device?", {"Keyboard", "Mouse", "Monitor", "Scanner"}, 2},
    {"What is the function of a motherboard?", {"Connect and manage hardware components", "Store files", "Process data", "Execute commands"}, 0},
    {"What does 'URL' stand for?", {"Uniform Resource Locator", "Universal Resource Locator", "Uniform Realtime Locator", "Universal Resource Locator"}, 0},
    {"Which of these is used for programming a website?", {"HTML", "Python", "Java", "JavaScript"}, 0},
    {"What does 'USB' stand for?", {"Universal Serial Bus", "Uniform Serial Bus", "Universal System Bus", "Universal Service Bus"}, 0},
    {"Which of the following is NOT a part of the software development life cycle?", {"Analysis", "Design", "Debugging", "Testing"}, 2},
    {"What is a variable in programming?", {"A storage location in memory with a name", "A type of loop", "A function that stores values", "A type of algorithm"}, 0},
    {"Which of these is a programming language?", {"Python", "Photoshop", "Microsoft Word", "Excel"}, 0},
    {"What does 'int' represent in most programming languages?", {"Integer", "Interval", "Instruction", "Internet"}, 0},
    {"What is the purpose of a function in programming?", {"To group code that performs a specific task", "To store data", "To define a variable", "To handle input/output operations"}, 0},
    {"Which of these is a correct example of a variable declaration in Python?", {"x = 10", "int x = 10", "let x = 10", "var x = 10"}, 0},
    {"What does 'if' do in a program?", {"It executes a block of code based on a condition", "It defines a function", "It stores data", "It creates an object"}, 0},
    {"Which of these is a type of loop?", {"for loop", "variable loop", "math loop", "exit loop"}, 0},
    {"What is the purpose of a 'while' loop?", {"To repeat a block of code as long as a condition is true", "To store data", "To define a function", "To display a message"}, 0},
    {"What does 'array' mean in programming?", {"A collection of elements, typically of the same type", "A function to calculate values", "A type of variable", "A mathematical operation"}, 0},
    {"What is a 'string' in programming?", {"A sequence of characters", "A collection of numbers", "A variable type", "A type of loop"}, 0},
    {"What is the purpose of a 'break' statement in a loop?", {"To exit the loop", "To repeat the loop", "To define a condition", "To declare a variable"}, 0},
    {"Which of the following is NOT a valid data type?", {"boolean", "integer", "character", "loop"}, 3},
    {"What does the 'else' statement do?", {"It specifies a block of code to run when the 'if' condition is false", "It starts a loop", "It defines a variable", "It ends a function"}, 0},
    {"Which of these is used to comment a line of code in Python?", {"# Comment", "// Comment", "/* Comment */", "<!-- Comment -->"}, 0},
    {"What does 'return' do in a function?", {"It exits the function and sends a value back", "It starts a new loop", "It defines a new variable", "It handles user input"}, 0},
    {"Which of the following is a logical operator?", {"&&", "++", "==", "-="}, 0},
    {"What is an object in Object-Oriented Programming (OOP)?", {"An instance of a class", "A variable", "A function", "A data type"}, 0},
    {"What does 'class' mean in OOP?", {"A blueprint for creating objects", "A collection of variables", "A function", "A type of loop"}, 0},
    {"What is the result of the following code snippet: `print(2 + 3 * 4)` in Python?", {"14", "20", "8", "24"}, 0},
    {"What does 'def' do in Python?", {"Defines a function", "Declares a variable", "Starts a loop", "Checks a condition"}, 0},
    {"Which of these is a type of operator in programming?", {"Arithmetic", "Function", "Variable", "Loop"}, 0},
    {"What is the purpose of a 'for' loop?", {"To iterate over a sequence of elements", "To store data", "To define variables", "To exit a loop"}, 0},
    {"What does 'continue' do in a loop?", {"Skips the current iteration and moves to the next one", "Exits the loop", "Starts the loop over", "Executes the loop condition"}, 0},
    {"What is the syntax for a comment in C++?", {"// Comment", "# Comment", "/* Comment */", "<!-- Comment -->"}, 0},
    {"Which of the following is an example of a comparison operator?", {"==", "=", "+", "*"}, 0},
    {"What is recursion in programming?", {"A function calling itself", "A loop that repeats", "A data structure", "A variable assignment"}, 0},
    {"Which of these is used to store multiple values in a single variable in most languages?", {"Array", "Variable", "Function", "String"}, 0},
    {"What does 'elif' do in Python?", {"It is used to check another condition if the 'if' is false", "It is a function", "It ends a loop", "It defines a variable"}, 0},
    {"What is the purpose of the 'try' block?", {"To handle exceptions or errors", "To declare a variable", "To define a function", "To start a loop"}, 0},
    {"Which of these is an example of an immutable data type in Python?", {"String", "List", "Dictionary", "Set"}, 0},
    {"What is the correct way to create a function in JavaScript?", {"function myFunction() {}", "create myFunction() {}", "def myFunction() {}", "function: myFunction() {}"}, 0},
    {"What is the correct syntax for an 'if' statement in Python?", {"if condition:", "if (condition) {}", "if [condition]", "if condition then"}, 0},
    {"What is an algorithm?", {"A step-by-step procedure to solve a problem", "A type of loop", "A function that executes code", "A data structure"}, 0},
    {"What is the purpose of the 'else if' statement?", {"To check additional conditions if the initial 'if' condition is false", "To start a loop", "To define a new variable", "To exit a loop"}, 0},
    {"What does 'boolean' represent?", {"True or false values", "Whole numbers", "Floating point numbers", "Text data"}, 0},
    {"Which of the following is an example of a 'while' loop in Python?", {"while condition:", "for condition:", "do condition while:", "repeat condition until:"}, 0},
    {"What is a method in Object-Oriented Programming?", {"A function defined inside a class", "A type of loop", "A variable", "A class definition"}, 0},
    {"What does 'null' represent?", {"A variable with no value assigned", "A function", "A type of data", "An empty list"}, 0},
    {"Which of these is a valid Python list?", {"[1, 2, 3]", "{1, 2, 3}", "(1, 2, 3)", "[1; 2; 3]"}, 0},
    {"What is a constructor in Object-Oriented Programming?", {"A method used to initialize an object", "A function", "A loop", "A variable"}, 0},
    {"What does 'assert' do in Python?", {"Checks if a condition is true and raises an error if not", "Declares a variable", "Defines a function", "Starts a loop"}, 0},
    {"Which of these is a type of data structure?", {"Linked list", "Variable", "Function", "Operator"}, 0},
    {"What is the result of `5 // 2` in Python?", {"2", "2.5", "3", "5"}, 0},
    {"Which of these is an example of a 'for' loop in Python?", {"for i in range(10):", "for i = 0; i < 10; i++", "for (i = 0; i < 10; i++)", "for i: 1 to 10"}, 0},
    {"What is an exception in programming?", {"An error that occurs during program execution", "A type of loop", "A method", "A data structure"}, 0},
    {"What is a 'class' in Object-Oriented Programming?", {"A blueprint for creating objects", "A type of function", "A variable type", "A data structure"}, 0},
    {"What does 'break' do in a loop?", {"Exits the loop", "Repeats the loop", "Defines a new variable", "Starts a new loop iteration"}, 0},
    {"Which of the following is an example of a function?", {"def myFunction():", "int x = 10", "for i in range(10):", "print(x)"}, 0},
    {"What is the purpose of the 'return' keyword?", {"To send a value from a function back to the caller", "To exit a loop", "To define a variable", "To start a function"}, 0},
    {"Which of these is an example of a 'dictionary' in Python?", {"{'key': 'value'}", "[1, 2, 3]", "{1, 2, 3}", "(1, 2, 3)"}, 0},
    {"What is a loop in programming?", {"A control structure that repeats code until a condition is met", "A type of variable", "A method of input validation", "A data structure"}, 0},
    {"Which of the following is used to define a function in Python?", {"def", "function", "func", "create"}, 0},
    {"What does 'else' represent in an 'if' statement?", {"Code that executes when the 'if' condition is false", "Code that always executes", "A variable assignment", "A loop control statement"}, 0},
    {"Which of the following is an example of a 'for' loop in Python?", {"for i in range(5):", "for (i = 0; i < 5; i++)", "loop i = 0; i < 5;", "repeat i until 5"}, 0},
    {"Which data structure uses key-value pairs?", {"Dictionary", "List", "Array", "String"}, 0},
    {"What is the purpose of the 'continue' statement?", {"To skip the current iteration and continue with the next one", "To exit the loop", "To define a function", "To declare a variable"}, 0},
    {"What is an exception?", {"An error that occurs during program execution", "A loop that repeats indefinitely", "A function that takes input", "A type of variable"}, 0},
    {"What does '==' mean in most programming languages?", {"Equality comparison", "Assignment", "Addition", "Modulo"}, 0},
    {"Which of these is used to store a sequence of characters?", {"String", "List", "Set", "Array"}, 0},
    {"What is the term for when a function calls itself?", {"Recursion", "Iteration", "Abstraction", "Inheritance"}, 0},
    {"Which of these is an example of a 'while' loop?", {"while condition:", "for i in range(10):", "repeat until condition;", "loop condition until true;"}, 0},
    {"What is the purpose of a class in Object-Oriented Programming?", {"To define the blueprint for creating objects", "To store data", "To perform operations on data", "To iterate through data"}, 0},
    {"What does the 'break' statement do in a loop?", {"Exits the loop immediately", "Skips the current iteration", "Defines a new function", "Declares a variable"}, 0},
    {"What is the difference between '==' and '===' in programming?", {"'==' compares values, '===' compares both values and types", "'==' compares types, '===' compares values", "'==' is used for functions, '===' for loops", "'==' is an assignment operator, '===' is a comparison"}, 0},
    {"What is an array?", {"A collection of elements of the same type", "A function that performs an operation", "A variable that stores data", "A conditional statement"}, 0},
    {"Which of these is an example of a 'for' loop in C++?", {"for(int i = 0; i < 10; i++)", "for i = 0 to 10", "repeat 10 times", "for i in range(10):"}, 0},
    {"What is a boolean data type?", {"A data type that can be either True or False", "A data type that stores text", "A data type used for floating-point numbers", "A data type used to store integers"}, 0},
    {"Which of these is a valid Python dictionary?", {"{'key': 'value'}", "[key: value]", "<key, value>", "(key = value)"}, 0},
    {"What does the 'input' function do in Python?", {"Accepts user input from the console", "Outputs data to the console", "Stores data in a variable", "Executes a function"}, 0},
    {"What is an identifier in programming?", {"A name given to variables, functions, or other elements", "A keyword in programming", "A special type of operator", "A kind of data structure"}, 0},
    {"Which of these is used for looping in Python?", {"for", "loop", "while", "both A and C"}, 3},
    {"What is an operator in programming?", {"A symbol that performs an operation on variables or values", "A variable in a program", "A function that performs a task", "A type of data structure"}, 0},
    {"What is the term for a function that returns another function?", {"Higher-order function", "Recursive function", "Anonymous function", "Nested function"}, 0},
    {"What is the purpose of the 'return' statement?", {"To send a result back from a function", "To exit a loop", "To define a variable", "To perform a calculation"}, 0},
    {"Which of these is an example of an immutable data type?", {"String", "List", "Dictionary", "Set"}, 0},
    {"What is the difference between '&&' and 'and' in programming?", {"'&&' is used in some languages (like C++), while 'and' is used in Python", "'&&' is for logical negation, 'and' for comparison", "'&&' and 'and' are the same", "'&&' is used for strings, 'and' for numbers"}, 0},
    {"Which of the following is a programming language?", {"JavaScript", "Java", "Ruby", "All of the above"}, 3},
    {"What does 'elif' stand for in Python?", {"Else if", "Else loop", "Else inline", "Else conditional"}, 0},
    {"Which of the following is an example of a conditional statement?", {"if", "for", "while", "def"}, 0},
    {"What is the purpose of the 'else' clause?", {"It defines code to execute if the condition is false", "It defines code to execute if the condition is true", "It breaks a loop", "It returns a result from a function"}, 0},
    {"Which of the following is a type of error in programming?", {"Syntax error", "Runtime error", "Logic error", "All of the above"}, 3},
    {"What is a method in Object-Oriented Programming?", {"A function that is associated with an object", "A type of variable", "A loop that repeats actions", "A conditional statement"}, 0},
    {"What does 'continue' do in a loop?", {"It skips the current iteration and continues with the next one", "It exits the loop", "It starts a new loop", "It defines a condition for the loop"}, 0},
    {"What is the purpose of the 'pass' statement in Python?", {"To do nothing, used as a placeholder", "To return a value", "To exit a loop", "To define a class"}, 0},
    {"Which of these is an example of a 'while' loop?", {"while i < 10:", "for i in range(10):", "repeat i until 10", "for i = 0; i < 10; i++"}, 0},
    {"Which of these is an example of a function in JavaScript?", {"function myFunction() {}", "myFunction function {}", "func myFunction() {}", "function: myFunction() {}"}, 0},
    {"What is the purpose of the 'break' statement in Python?", {"It exits the current loop", "It defines a function", "It starts a new iteration", "It skips the loop's current iteration"}, 0},
    {"Which of the following is an example of a logical operator?", {"and", "or", "not", "All of the above"}, 3},
    {"What is a nested loop?", {"A loop inside another loop", "A loop with multiple conditions", "A loop that calls a function", "A loop that iterates over multiple variables"}, 0},
    {"Which of the following is used to define a function in Java?", {"public static void myFunction()", "def myFunction()", "function myFunction()", "func myFunction()"}, 0},
    {"What does the 'input()' function do in Python?", {"It reads a line of text from the user", "It displays text to the user", "It stores user input in a variable", "It executes a function"}, 0},
    {"What is the default value of an uninitialized variable in JavaScript?", {"undefined", "null", "0", "NaN"}, 0},
    {"Which of these is used to loop through a range of numbers in Python?", {"range()", "loop()", "iterate()", "repeat()"}, 0},
    {"What is the purpose of the 'global' keyword in Python?", {"To declare a global variable inside a function", "To define a global function", "To iterate through global variables", "To access local variables globally"}, 0},
    {"What is the result of the following expression: `5 % 2`?", {"1", "2", "5", "0"}, 0},
    {"Which of the following is NOT a valid variable name in Python?", {"2ndVariable", "_variable", "variable2", "variable_name"}, 0},
    {"What does 'else if' represent in most programming languages?", {"A conditional statement that checks another condition", "A loop", "A method", "A data structure"}, 0},
    {"What is the use of the 'try' block?", {"To handle exceptions in a program", "To define a function", "To declare variables", "To start a loop"}, 0},
    {"What does the term 'iteration' refer to in programming?", {"Repeating a block of code multiple times", "Defining a function", "Declaring a variable", "Handling errors"}, 0}
    //----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

};

std::vector<Question> GetQuestionsVector() {
    return questions;
}
